name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: true
      matrix:
        php: [7.3, 7.4, 8.0, 8.1, 8.2]
        laravel: [8.0, 9.0, 10.0]
        exclude:
          - php: 7.3
            laravel: 9.0
          - php: 7.3
            laravel: 10.0
          - php: 7.4
            laravel: 9.0
          - php: 7.4
            laravel: 10.0
          - php: 8.0
            laravel: 10.0
          - php: 8.2
            laravel: 8.0

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Docs: https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: sqlite3
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Setup problem matchers for PHP/PHPUnit
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts=^${{ matrix.laravel }}" --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Execute test suite
        run: vendor/bin/phpunit
